FROM ARG_FROM

MAINTAINER TIP <postmottak.tip@trondheim.kommune.no>

ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN

RUN apk add --no-cache tzdata
ENV TZ=Europe/Oslo

RUN apk --no-cache add curl
RUN apk --no-cache add openssl

USER root:root
ENTRYPOINT ["/ARG_BIN"]
HEALTHCHECK --interval=20s --timeout=3s CMD curl --fail http://localhost:8090/health || exit 1
